#!/usr/bin/env python3
"""
models.py
---------
The canonical domain models and type definitions for the LithoStepper LS-200 
Adapter framework. This module contains zero network, protocol, or library 
dependencies beyond standard Python typing libraries.
"""

from datetime import datetime
from enum import Enum
from typing import Dict, Any, Optional, List


class RecordType(str, Enum):
    """Enumeration of the four fundamental log line types emitted by the tool."""
    STATE = "STATE"
    EVENT = "EVENT"
    TELEM = "TELEM"
    ALARM = "ALARM"


class ParsedRecord:
    """
    The immutable Data Transfer Object (DTO) generated by Layer 1 (Parser).
    Represents a successfully validated envelope containing a single log entry.
    """
    def __init__(self, timestamp: datetime, record_type: RecordType, payload: Dict[str, str]):
        self.timestamp: datetime = timestamp
        self.record_type: RecordType = record_type
        self.payload: Dict[str, str] = payload

    def __repr__(self) -> str:
        return f"ParsedRecord(ts={self.timestamp.isoformat()}, type={self.record_type.value}, fields={len(self.payload)})"


class CanonicalState:
    """
    The heart of the application (Layer 2). Represents a stateful, structured 
    snapshot of the photolithography tool at any given instant in time. 
    
    This object is modified incrementally by incoming ParsedRecords and read 
    by external Interface Projections (Layer 3).
    """
    def __init__(self):
        # --- SEMI E10 Operational States ---
        self.current_state: str = "NON_SCHEDULED"
        self.previous_state: str = "NON_SCHEDULED"
        self.state_changed_at: Optional[datetime] = None

        # --- Active Production Context ---
        self.current_lot: Optional[str] = None
        self.current_wafer: Optional[str] = None
        self.current_slot: Optional[str] = None
        self.recipe: Optional[str] = None
        self.reticle: Optional[str] = None
        
        # --- Historical/Batch Context ---
        self.expected_wafers_in_lot: Optional[int] = None
        self.latest_alignment_residual_nm: Optional[float] = None
        self.latest_exposure_fields: Optional[int] = None
        self.latest_exposure_dose_mj_cm2: Optional[float] = None

        # --- Active Alarms Map ---
        # Schema: { alid_string: { "severity": str, "text": str, "set_at": datetime } }
        self.active_alarms: Dict[str, Dict[str, Any]] = {}

        # --- High-Frequency Telemetry Cache ---
        self.telemetry: Dict[str, float] = {
            "stage_temp_c": 0.0,
            "chuck_vac_kpa": 0.0,
            "laser_mj": 0.0,
            "illum_pct": 0.0,
            "focus_nm": 0.0
        }
        
        # --- Robustness & Health Statistics ---
        self.total_processed_lines: int = 0
        self.malformed_lines_count: int = 0
        self.last_updated_at: Optional[datetime] = None

    def to_dict(self) -> Dict[str, Any]:
        """
        Helper serialization utility. Allows easy translation into downstream 
        protocol formats (like HTTP/JSON or WebSockets) without binding network 
        logic to the class itself.
        """
        return {
            "equipment": {
                "current_state": self.current_state,
                "previous_state": self.previous_state,
                "last_state_change": self.state_changed_at.isoformat() if self.state_changed_at else None,
            },
            "production_context": {
                "current_lot": self.current_lot,
                "current_wafer": self.current_wafer,
                "current_slot": self.current_slot,
                "recipe": self.recipe,
                "reticle": self.reticle,
                "expected_wafers": self.expected_wafers_in_lot,
                "metrics": {
                    "last_align_residual_nm": self.latest_alignment_residual_nm,
                    "last_fields_count": self.latest_exposure_fields,
                    "last_dose_mj_cm2": self.latest_exposure_dose_mj_cm2
                }
            },
            "active_alarms": [
                {
                    "alid": alid,
                    "severity": info["severity"],
                    "text": info["text"],
                    "set_at": info["set_at"].isoformat()
                }
                for alid, info in self.active_alarms.items()
            ],
            "telemetry": self.telemetry.copy(),
            "adapter_metrics": {
                "total_processed_lines": self.total_processed_lines,
                "malformed_lines_count": self.malformed_lines_count,
                "last_updated_at": self.last_updated_at.isoformat() if self.last_updated_at else None
            }
        }

    def __repr__(self) -> str:
        return (f"CanonicalState(State={self.current_state}, Lot={self.current_lot}, "
                f"Wafer={self.current_wafer}, ActiveAlarms={len(self.active_alarms)}, "
                f"Errors={self.malformed_lines_count})")